        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Eduardo
 */
public class miVISTA extends javax.swing.JFrame {

    /**
     * Creates new form miVISTA
     */
    public miVISTA() {
        
        this.setUndecorated(true);
        initComponents();
        PANELIMAGEN.setOpaque(false);
        //PANELQR.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4_MENSAJEPUERTO = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        PANELIMAGEN = new javax.swing.JPanel();
        jLabel4IMAGENUSUARIO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        SALIR = new javax.swing.JButton();
        BQR = new javax.swing.JButton();
        BPDF = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bOK = new javax.swing.JButton();
        jLabel3VOZ = new javax.swing.JLabel();
        jButton1MOVE_BACK = new javax.swing.JButton();
        jButton1MOVE_NEXT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1_UPDATE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1_SELECT_FRECUENCIA = new javax.swing.JButton();
        jButton2_ON = new javax.swing.JButton();
        jButton3OFF = new javax.swing.JButton();
        jButton1WRITE_TAG = new javax.swing.JButton();
        jLabel5LOGIN = new javax.swing.JLabel();
        jTextField5Contrasena = new javax.swing.JTextField();
        jTextField6Universidad = new javax.swing.JTextField();
        jTextField4Correo = new javax.swing.JTextField();
        jTextField3Nombre = new javax.swing.JTextField();
        jTextField4_ID = new javax.swing.JTextField();
        jLabel4CODEQR = new javax.swing.JLabel();
        jButton1_INSERT = new javax.swing.JButton();
        jbutton_NEW = new javax.swing.JButton();
        jTextField3_ID_CONFERENCIA = new javax.swing.JTextField();
        jTextField4_TITULO_CONFE = new javax.swing.JTextField();
        jTextField5_CONFERENCISTA = new javax.swing.JTextField();
        jButton1_INSERT_CONFE = new javax.swing.JButton();
        jTextField3_ID_PARTPNTE_REG = new javax.swing.JTextField();
        jTextField4_ID_CONFE_REG = new javax.swing.JTextField();
        jTextField5_FECHA_REG = new javax.swing.JTextField();
        jTextField6_HORA_REG = new javax.swing.JTextField();
        jButton_REGISTRAR_REG = new javax.swing.JButton();
        jButton1_ACTIVAR_REG = new javax.swing.JButton();
        jButton1_BACK_CONFE = new javax.swing.JButton();
        jButton2_NEXT_CONFE = new javax.swing.JButton();
        jButton1UPCONF = new javax.swing.JButton();
        jButton1NUEVA_CONFER = new javax.swing.JButton();
        jLabel4SUPER_ON = new javax.swing.JLabel();
        jLabel4_SUPEROFF = new javax.swing.JLabel();
        jButton1PARAR_REGISTRO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel4_MENSAJEPUERTO);
        jLabel4_MENSAJEPUERTO.setBounds(820, 470, 520, 20);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 110, 220, 20);

        PANELIMAGEN.setBackground(new java.awt.Color(102, 102, 255));
        PANELIMAGEN.setLayout(null);
        PANELIMAGEN.add(jLabel4IMAGENUSUARIO);
        jLabel4IMAGENUSUARIO.setBounds(0, 0, 160, 170);

        jPanel1.add(PANELIMAGEN);
        PANELIMAGEN.setBounds(90, 30, 160, 170);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("TEXTO A CODIFICAR:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(790, 60, 170, 24);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(660, 110, 300, 20);

        SALIR.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSALR.png"))); // NOI18N
        SALIR.setText("Salir");
        SALIR.setBorder(null);
        SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(SALIR);
        SALIR.setBounds(1090, 0, 100, 50);

        BQR.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        BQR.setForeground(new java.awt.Color(51, 51, 51));
        BQR.setText("Generar");
        BQR.setBorder(null);
        BQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQRActionPerformed(evt);
            }
        });
        jPanel1.add(BQR);
        BQR.setBounds(510, 410, 30, 40);

        BPDF.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        BPDF.setForeground(new java.awt.Color(51, 51, 51));
        BPDF.setText("pdf");
        BPDF.setBorder(null);
        BPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPDFActionPerformed(evt);
            }
        });
        jPanel1.add(BPDF);
        BPDF.setBounds(450, 410, 40, 40);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EDUARDO MARTINEZ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1242, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 720, 1360, 40);

        bOK.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        bOK.setForeground(new java.awt.Color(102, 102, 102));
        bOK.setText("OK");
        bOK.setBorder(null);
        bOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bOK);
        bOK.setBounds(530, 170, 110, 110);

        jLabel3VOZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/voz4.gif"))); // NOI18N
        jPanel1.add(jLabel3VOZ);
        jLabel3VOZ.setBounds(1210, 0, 150, 30);

        jButton1MOVE_BACK.setForeground(new java.awt.Color(228, 232, 232));
        jButton1MOVE_BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDBACK.png"))); // NOI18N
        jButton1MOVE_BACK.setText("BACK");
        jButton1MOVE_BACK.setBorder(null);
        jButton1MOVE_BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1MOVE_BACK);
        jButton1MOVE_BACK.setBounds(680, 500, 40, 50);

        jButton1MOVE_NEXT.setForeground(new java.awt.Color(228, 232, 232));
        jButton1MOVE_NEXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDNEXT.png"))); // NOI18N
        jButton1MOVE_NEXT.setText("NEXT");
        jButton1MOVE_NEXT.setBorder(null);
        jButton1MOVE_NEXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1MOVE_NEXT);
        jButton1MOVE_NEXT.setBounds(910, 500, 40, 50);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 204, 204));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(0, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Correo", "Constrasena", "Universidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 480, 480, 100);

        jButton1_UPDATE.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDUPDATE.png"))); // NOI18N
        jButton1_UPDATE.setText("UPDATE");
        jButton1_UPDATE.setBorder(null);
        jButton1_UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_UPDATE);
        jButton1_UPDATE.setBounds(800, 500, 40, 50);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("P U E R T O   A C T I V O");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1210, 110, 140, 17);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(0, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(1200, 200, 150, 24);

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setForeground(new java.awt.Color(0, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(1200, 230, 150, 140);

        jButton1_SELECT_FRECUENCIA.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_SELECT_FRECUENCIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PUERTCOM.png"))); // NOI18N
        jButton1_SELECT_FRECUENCIA.setText("INICIO");
        jButton1_SELECT_FRECUENCIA.setBorder(null);
        jButton1_SELECT_FRECUENCIA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1_SELECT_FRECUENCIA);
        jButton1_SELECT_FRECUENCIA.setBounds(1240, 140, 70, 40);

        jButton2_ON.setForeground(new java.awt.Color(228, 232, 232));
        jButton2_ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDON2.png"))); // NOI18N
        jButton2_ON.setText("ON");
        jButton2_ON.setBorder(null);
        jButton2_ON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton2_ON);
        jButton2_ON.setBounds(1200, 410, 70, 40);

        jButton3OFF.setForeground(new java.awt.Color(228, 232, 232));
        jButton3OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDOFF2.png"))); // NOI18N
        jButton3OFF.setText("OFF");
        jButton3OFF.setBorder(null);
        jButton3OFF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3OFF);
        jButton3OFF.setBounds(1290, 410, 70, 40);

        jButton1WRITE_TAG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDW.png"))); // NOI18N
        jButton1WRITE_TAG.setText("WRITE");
        jButton1WRITE_TAG.setBorder(null);
        jButton1WRITE_TAG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1WRITE_TAG);
        jButton1WRITE_TAG.setBounds(30, 270, 120, 60);

        jLabel5LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movazul.gif"))); // NOI18N
        jPanel1.add(jLabel5LOGIN);
        jLabel5LOGIN.setBounds(1010, 240, 128, 160);

        jTextField5Contrasena.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField5Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5Contrasena.setBorder(null);
        jPanel1.add(jTextField5Contrasena);
        jTextField5Contrasena.setBounds(710, 350, 220, 20);

        jTextField6Universidad.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField6Universidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6Universidad.setBorder(null);
        jTextField6Universidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6UniversidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6Universidad);
        jTextField6Universidad.setBounds(710, 380, 220, 20);

        jTextField4Correo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField4Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4Correo.setBorder(null);
        jTextField4Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4CorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4Correo);
        jTextField4Correo.setBounds(710, 320, 220, 20);

        jTextField3Nombre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField3Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3Nombre.setBorder(null);
        jTextField3Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3NombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3Nombre);
        jTextField3Nombre.setBounds(710, 290, 220, 20);

        jTextField4_ID.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jTextField4_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4_ID.setBorder(null);
        jPanel1.add(jTextField4_ID);
        jTextField4_ID.setBounds(710, 250, 220, 20);
        jPanel1.add(jLabel4CODEQR);
        jLabel4CODEQR.setBounds(670, 190, 290, 270);

        jButton1_INSERT.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_INSERT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PARTICI.png"))); // NOI18N
        jButton1_INSERT.setText("INSERT");
        jButton1_INSERT.setBorder(null);
        jButton1_INSERT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1_INSERT);
        jButton1_INSERT.setBounds(860, 500, 40, 50);

        jbutton_NEW.setForeground(new java.awt.Color(228, 232, 232));
        jbutton_NEW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDCLEAN.png"))); // NOI18N
        jbutton_NEW.setText("NEW");
        jbutton_NEW.setBorder(null);
        jbutton_NEW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jbutton_NEW);
        jbutton_NEW.setBounds(740, 510, 40, 40);

        jTextField3_ID_CONFERENCIA.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3_ID_CONFERENCIA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3_ID_CONFERENCIA.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(jTextField3_ID_CONFERENCIA);
        jTextField3_ID_CONFERENCIA.setBounds(40, 350, 120, 20);

        jTextField4_TITULO_CONFE.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4_TITULO_CONFE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4_TITULO_CONFE.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(jTextField4_TITULO_CONFE);
        jTextField4_TITULO_CONFE.setBounds(170, 350, 250, 19);

        jTextField5_CONFERENCISTA.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5_CONFERENCISTA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5_CONFERENCISTA.setForeground(new java.awt.Color(0, 153, 204));
        jTextField5_CONFERENCISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_CONFERENCISTAActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5_CONFERENCISTA);
        jTextField5_CONFERENCISTA.setBounds(430, 350, 110, 19);

        jButton1_INSERT_CONFE.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_INSERT_CONFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CONFE.png"))); // NOI18N
        jButton1_INSERT_CONFE.setText("INSERTC");
        jButton1_INSERT_CONFE.setBorder(null);
        jButton1_INSERT_CONFE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_INSERT_CONFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_INSERT_CONFEActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_INSERT_CONFE);
        jButton1_INSERT_CONFE.setBounds(290, 400, 50, 50);

        jTextField3_ID_PARTPNTE_REG.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3_ID_PARTPNTE_REG.setForeground(new java.awt.Color(0, 153, 153));
        jTextField3_ID_PARTPNTE_REG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3_ID_PARTPNTE_REG.setBorder(null);
        jPanel1.add(jTextField3_ID_PARTPNTE_REG);
        jTextField3_ID_PARTPNTE_REG.setBounds(1100, 510, 250, 15);

        jTextField4_ID_CONFE_REG.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4_ID_CONFE_REG.setForeground(new java.awt.Color(0, 153, 153));
        jTextField4_ID_CONFE_REG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4_ID_CONFE_REG.setBorder(null);
        jPanel1.add(jTextField4_ID_CONFE_REG);
        jTextField4_ID_CONFE_REG.setBounds(1100, 550, 250, 15);

        jTextField5_FECHA_REG.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5_FECHA_REG.setForeground(new java.awt.Color(0, 153, 153));
        jTextField5_FECHA_REG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5_FECHA_REG.setBorder(null);
        jTextField5_FECHA_REG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_FECHA_REGActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5_FECHA_REG);
        jTextField5_FECHA_REG.setBounds(1100, 590, 250, 15);

        jTextField6_HORA_REG.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6_HORA_REG.setForeground(new java.awt.Color(0, 153, 153));
        jTextField6_HORA_REG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6_HORA_REG.setBorder(null);
        jPanel1.add(jTextField6_HORA_REG);
        jTextField6_HORA_REG.setBounds(1100, 630, 250, 15);

        jButton_REGISTRAR_REG.setForeground(new java.awt.Color(228, 232, 232));
        jButton_REGISTRAR_REG.setText("REGISTRAR");
        jButton_REGISTRAR_REG.setBorder(null);
        jButton_REGISTRAR_REG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_REGISTRAR_REG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_REGISTRAR_REGActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_REGISTRAR_REG);
        jButton_REGISTRAR_REG.setBounds(760, 610, 80, 70);

        jButton1_ACTIVAR_REG.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_ACTIVAR_REG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ENCENDER.png"))); // NOI18N
        jButton1_ACTIVAR_REG.setText("ActivarReg");
        jButton1_ACTIVAR_REG.setBorder(null);
        jButton1_ACTIVAR_REG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1_ACTIVAR_REG);
        jButton1_ACTIVAR_REG.setBounds(1290, 670, 50, 40);

        jButton1_BACK_CONFE.setForeground(new java.awt.Color(228, 232, 232));
        jButton1_BACK_CONFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDBACK.png"))); // NOI18N
        jButton1_BACK_CONFE.setText("BCO");
        jButton1_BACK_CONFE.setBorder(null);
        jButton1_BACK_CONFE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_BACK_CONFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BACK_CONFEActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_BACK_CONFE);
        jButton1_BACK_CONFE.setBounds(60, 410, 30, 30);

        jButton2_NEXT_CONFE.setForeground(new java.awt.Color(228, 232, 232));
        jButton2_NEXT_CONFE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDNEXT.png"))); // NOI18N
        jButton2_NEXT_CONFE.setText("NCO");
        jButton2_NEXT_CONFE.setBorder(null);
        jButton2_NEXT_CONFE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_NEXT_CONFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_NEXT_CONFEActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_NEXT_CONFE);
        jButton2_NEXT_CONFE.setBounds(110, 410, 30, 30);

        jButton1UPCONF.setForeground(new java.awt.Color(228, 232, 232));
        jButton1UPCONF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDUPDATE.png"))); // NOI18N
        jButton1UPCONF.setText("UPCONFE");
        jButton1UPCONF.setBorder(null);
        jButton1UPCONF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1UPCONF);
        jButton1UPCONF.setBounds(190, 410, 40, 30);

        jButton1NUEVA_CONFER.setForeground(new java.awt.Color(228, 232, 232));
        jButton1NUEVA_CONFER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RFIDCLEAN.png"))); // NOI18N
        jButton1NUEVA_CONFER.setText("NC");
        jButton1NUEVA_CONFER.setBorder(null);
        jButton1NUEVA_CONFER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1NUEVA_CONFER);
        jButton1NUEVA_CONFER.setBounds(240, 410, 40, 30);

        jLabel4SUPER_ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ONSUPER.png"))); // NOI18N
        jPanel1.add(jLabel4SUPER_ON);
        jLabel4SUPER_ON.setBounds(1150, 660, 130, 60);

        jLabel4_SUPEROFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OFFSUPER.png"))); // NOI18N
        jPanel1.add(jLabel4_SUPEROFF);
        jLabel4_SUPEROFF.setBounds(1150, 660, 130, 60);

        jButton1PARAR_REGISTRO.setForeground(new java.awt.Color(228, 232, 232));
        jButton1PARAR_REGISTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ENCENDER.png"))); // NOI18N
        jButton1PARAR_REGISTRO.setText("PararR");
        jPanel1.add(jButton1PARAR_REGISTRO);
        jButton1PARAR_REGISTRO.setBounds(1080, 670, 60, 40);

        jLabel4.setForeground(new java.awt.Color(228, 232, 232));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo01.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1360, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BQRActionPerformed

    private void BPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPDFActionPerformed

    private void jTextField6UniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6UniversidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6UniversidadActionPerformed

    private void jTextField4CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4CorreoActionPerformed

    private void jButton1_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_UPDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_UPDATEActionPerformed

    private void jTextField3NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3NombreActionPerformed

    private void jTextField5_CONFERENCISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_CONFERENCISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_CONFERENCISTAActionPerformed

    private void jButton1_INSERT_CONFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_INSERT_CONFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_INSERT_CONFEActionPerformed

    private void jButton2_NEXT_CONFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_NEXT_CONFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_NEXT_CONFEActionPerformed

    private void jButton1_BACK_CONFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BACK_CONFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_BACK_CONFEActionPerformed

    private void jTextField5_FECHA_REGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_FECHA_REGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_FECHA_REGActionPerformed

    private void jButton_REGISTRAR_REGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_REGISTRAR_REGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_REGISTRAR_REGActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BPDF;
    public javax.swing.JButton BQR;
    public javax.swing.JPanel PANELIMAGEN;
    public javax.swing.JButton SALIR;
    public javax.swing.JButton bOK;
    public javax.swing.JButton jButton1MOVE_BACK;
    public javax.swing.JButton jButton1MOVE_NEXT;
    public javax.swing.JButton jButton1NUEVA_CONFER;
    public javax.swing.JButton jButton1PARAR_REGISTRO;
    public javax.swing.JButton jButton1UPCONF;
    public javax.swing.JButton jButton1WRITE_TAG;
    public javax.swing.JButton jButton1_ACTIVAR_REG;
    public javax.swing.JButton jButton1_BACK_CONFE;
    public javax.swing.JButton jButton1_INSERT;
    public javax.swing.JButton jButton1_INSERT_CONFE;
    public javax.swing.JButton jButton1_SELECT_FRECUENCIA;
    public javax.swing.JButton jButton1_UPDATE;
    public javax.swing.JButton jButton2_NEXT_CONFE;
    public javax.swing.JButton jButton2_ON;
    public javax.swing.JButton jButton3OFF;
    public javax.swing.JButton jButton_REGISTRAR_REG;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel3VOZ;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel4CODEQR;
    public javax.swing.JLabel jLabel4IMAGENUSUARIO;
    public javax.swing.JLabel jLabel4SUPER_ON;
    public javax.swing.JLabel jLabel4_MENSAJEPUERTO;
    public javax.swing.JLabel jLabel4_SUPEROFF;
    public javax.swing.JLabel jLabel5LOGIN;
    public javax.swing.JList jList1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3Nombre;
    public javax.swing.JTextField jTextField3_ID_CONFERENCIA;
    public javax.swing.JTextField jTextField3_ID_PARTPNTE_REG;
    public javax.swing.JTextField jTextField4Correo;
    public javax.swing.JTextField jTextField4_ID;
    public javax.swing.JTextField jTextField4_ID_CONFE_REG;
    public javax.swing.JTextField jTextField4_TITULO_CONFE;
    public javax.swing.JTextField jTextField5Contrasena;
    public javax.swing.JTextField jTextField5_CONFERENCISTA;
    public javax.swing.JTextField jTextField5_FECHA_REG;
    public javax.swing.JTextField jTextField6Universidad;
    public javax.swing.JTextField jTextField6_HORA_REG;
    public javax.swing.JButton jbutton_NEW;
    // End of variables declaration//GEN-END:variables
}
